(test
 (name test_set_fold)
 (modules test_set_fold)
 (libraries octra_core octra_consensus octra_net zarith
  mirage-crypto-ec mirage-crypto-rng.unix))

(test
 (name test_vote_log)
 (modules test_vote_log)
 (libraries octra_consensus unix))

(test
 (name test_bundle_cache)
 (modules test_bundle_cache)
 (libraries octra_node_runtime octra_core octra_consensus octra_net zarith yojson lwt.unix))

(test
 (name test_bft_validator_transition)
 (modules test_bft_validator_transition)
 (libraries octra_consensus octra_net lwt lwt.unix mirage-crypto-ec
  mirage-crypto-rng.unix))

(test
 (name test_tx_staging_selection)
 (modules test_tx_staging_selection)
 (libraries octra_core zarith unix))

(test
 (name test_admit)
 (modules test_admit)
 (libraries octra_core octra_node_runtime zarith unix yojson lwt.unix))

(test
 (name test_rule_graph)
 (modules test_rule_graph)
 (libraries octra_core))

(test
 (name test_account_pack)
 (modules test_account_pack)
 (libraries octra_core base64 zarith lwt.unix unix))

(test
 (name test_validator_lifecycle)
 (modules test_validator_lifecycle)
 (libraries octra_core zarith base64 yojson lwt.unix unix
  mirage-crypto-ec mirage-crypto-rng.unix))

(test
 (name test_lock_rule)
 (modules test_lock_rule)
 (libraries octra_net octra_consensus))

(test
 (name test_weighted_bft)
 (modules test_weighted_bft)
 (libraries octra_consensus octra_net zarith))

(test
 (name test_epoch_exec_reward_atomic)
 (modules test_epoch_exec_reward_atomic)
 (libraries octra_core octra_consensus octra_net octra_node_runtime
  base64 yojson zarith lwt.unix))

(test
 (name test_private_transition_receipt)
 (modules test_private_transition_receipt)
 (libraries octra_core octra_consensus octra_node_runtime pvac_ffi
  lwt lwt.unix unix base64 yojson zarith
  mirage-crypto-ec mirage-crypto-rng.unix)
 (action
  (setenv
   OCTRA_PVAC_VERIFY_WORKER
   %{exe:../bin/octra_pvac_worker.exe}
   (run %{test}))))

(test
 (name test_preverify_cache)
 (modules test_preverify_cache)
 (libraries octra_node_runtime lwt lwt.unix))

(test
 (name test_consensus_profile_golden)
 (modules test_consensus_profile_golden)
 (libraries octra_core octra_consensus octra_net octra_vm octra_circle_runtime octra_node_runtime))

(test
 (name test_join_rpc)
 (modules test_join_rpc)
 (libraries octra_node_runtime octra_core octra_consensus octra_net octra_bootstrap zarith lwt.unix))

(test
 (name test_catchup_shell)
 (modules test_catchup_shell)
 (libraries octra_node_runtime lwt lwt.unix))

(test
 (name test_proposal)
 (modules test_proposal)
 (libraries octra_node_runtime octra_core zarith))

(test
 (name test_driver_boot)
 (modules test_driver_boot)
 (libraries octra_node_runtime))

(test
 (name test_net_boot)
 (modules test_net_boot)
 (libraries octra_node_runtime octra_core octra_consensus))

(test
 (name test_store_growth)
 (modules test_store_growth)
 (libraries octra_core digestif irmin-pack lwt.unix zarith))

(test
 (name test_program_compile)
 (modules test_program_compile)
 (libraries octra_core octra_vm digestif zarith base64 pvac_ffi lwt.unix unix))

(test
 (name test_prior)
 (modules test_prior)
 (deps (glob_files ../lib/vm/compiler/prior/*.ml))
 (libraries octra_core octra_vm octra_circle_runtime digestif zarith base64 lwt.unix))

(test
 (name test_gc_head)
 (modules test_gc_head)
 (libraries octra_core octra_node_runtime lwt.unix))

(test
 (name test_txlog)
 (modules test_txlog)
 (libraries octra_core unix))

(test
 (name test_state_sync_reliability)
 (modules test_state_sync_reliability)
 (libraries octra_bootstrap octra_node_runtime unix))

(test
 (name test_grpc)
 (modules test_grpc)
 (libraries octra_core octra_node_runtime lwt.unix yojson pbrt))

(test
 (name test_epoch_page)
 (modules test_epoch_page)
 (libraries octra_core octra_node_runtime lwt.unix yojson pbrt mtime.clock.os))

(test
 (name test_grpc_http2)
 (modules test_grpc_http2)
 (libraries octra_core octra_node_runtime lwt.unix yojson pbrt h2 h2-lwt-unix bigstringaf))

(executables
 (names test_epoch_replay test_epoch_store replay)
 (modules test_epoch_replay test_epoch_store replay epoch_replay epoch_store)
 (libraries octra_core octra_consensus octra_node_runtime octra_bootstrap
  octra_vm lwt.unix yojson zarith digestif.c))

(rule
 (alias runtest)
 (action (run %{exe:test_epoch_replay.exe})))

(rule
 (alias runtest)
 (action (run %{exe:test_epoch_store.exe})))

(rule
 (target cipher_slots.exe)
 (deps cipher_slots.cpp ../pvac_ffi/pvac_serialize.hpp
  (source_tree ../pvac/include))
 (action
  (bash "ARCH=$(uname -m); AES_FLAGS=''; if [ \"$ARCH\" = 'x86_64' ]; then AES_FLAGS='-maes -msse2'; elif [ \"$ARCH\" = 'aarch64' ] || [ \"$ARCH\" = 'arm64' ]; then AES_FLAGS='-march=armv8-a+crypto'; fi; c++ -std=c++17 -O2 $AES_FLAGS -I../pvac/include -I../pvac_ffi %{dep:cipher_slots.cpp} -o %{target}")))

(rule
 (alias runtest)
 (action (run ./cipher_slots.exe)))

(rule
 (target native_math.exe)
 (deps native_math.cpp ../pvac_ffi/pvac_serialize.hpp
  (source_tree ../pvac/include))
 (action
  (bash "ARCH=$(uname -m); AES_FLAGS=''; if [ \"$ARCH\" = 'x86_64' ]; then AES_FLAGS='-maes -msse2'; elif [ \"$ARCH\" = 'aarch64' ] || [ \"$ARCH\" = 'arm64' ]; then AES_FLAGS='-march=armv8-a+crypto'; fi; c++ -std=c++17 -O2 -pthread $AES_FLAGS -I../pvac/include -I../pvac_ffi %{dep:native_math.cpp} -o %{target}")))

(rule
 (alias runtest)
 (action (run ./native_math.exe)))

(test
 (name test_pvac_verify_worker)
 (modules test_pvac_verify_worker)
 (deps ../bin/octra_pvac_worker.exe)
 (libraries octra_core lwt lwt.unix unix))

(test
 (name test_fixed_q16)
 (modules test_fixed_q16)
 (libraries octra_vm zarith))

(test
 (name test_circle_wasm_hfhe_policy)
 (modules test_circle_wasm_hfhe_policy)
 (libraries octra_core pvac_ffi))

(test
 (name test_contract_rpc_guard)
 (modules test_contract_rpc_guard)
 (libraries octra_vm unix lwt.unix base64 digestif))

(test
 (name test_circle_program_admission)
 (modules test_circle_program_admission)
 (libraries octra_core octra_circle_runtime octra_vm unix lwt lwt.unix yojson base64 zarith))

(test
 (name test_circle_view_cap)
 (modules test_circle_view_cap)
 (libraries octra_node_runtime lwt.unix))

(test
 (name test_node_runtime_tx_view)
 (modules test_node_runtime_tx_view)
 (deps ../bin/octra_pvac_worker.exe)
 (libraries octra_node_runtime octra_core yojson zarith))

(test
 (name test_node_runtime_p2p_tx_admit)
 (modules test_node_runtime_p2p_tx_admit)
 (libraries octra_node_runtime octra_core zarith base64 mirage-crypto-ec mirage-crypto-rng.unix))

(test
 (name test_aml_profile)
 (modules test_aml_profile)
 (libraries octra_vm base64 digestif zarith))

(test
 (name test_aml_program)
 (modules test_aml_program)
 (libraries octra_vm digestif zarith))

(test
 (name test_p2p_preauth)
 (modules test_p2p_preauth)
 (libraries octra_net lwt.unix mirage-crypto-ec mirage-crypto-rng.unix))

(test
 (name test_call_plan)
 (modules test_call_plan)
 (libraries octra_vm yojson zarith))

(test
 (name test_wasm_guard)
 (modules test_wasm_guard)
 (libraries octra_circle_runtime octra_core octra_vm lwt.unix zarith unix))

(test
 (name test_multi_exec)
 (modules test_multi_exec)
 (libraries octra_core octra_vm yojson zarith))

(test
 (name test_direct_exec)
 (modules test_direct_exec)
 (libraries octra_vm yojson zarith lwt lwt.unix))

(test
 (name test_set_actor)
 (modules test_set_actor)
 (libraries octra_node_runtime octra_core octra_consensus lwt.unix zarith))